#!/bin/sh

if [ -f packaging.sh ]; then
    . packaging.sh
else
    script_root=$(dirname $0);
    if [ -f ${script_root}/packaging.sh ]; then
	. ${script_root}/packaging.sh;
    else
	echo "Can't find packaging.sh init";
	exit 2;
    fi;
fi;

(sudo dpkg -i ${PKGNAME}_${REL_VERSION}*.deb) && (sudo dpkg -i ${PKGNAME}-*_${REL_VERSION}*.deb);
