#!/bin/sh

pkgname=${1:-${PKGNAME}}
usedir=${2:-${pkgname}}
distro=${3:-$(cat state/DISTRO || echo debian)}
status=${4:-$(cat state/STATUS || echo stable)}
urgency=${5:-$(cat state/URGENCY || echo normal)}

version=$(cat state/VERSION)
branch=$(cat state/BRANCH);
full_version=$(cat state/FULL_VERSION || echo $version);
major_version=$(cat state/MAJOR_VERSION || echo $version);
minor_version=$(cat state/MINOR_VERSION || echo $version);
base_version=$(cat state/BASE_VERSION || echo $version);


if [ "${usedir}" = "-" ]; then
    usedir=${pkgname};
elif [ "${usedir}" = "." ]; then
    usedir=${pkgname};
fi;

if [ -d ${usedir} ]; then echo "Removing current ${usedir}"; rm -rf ${usedir}; fi
mkdir ${usedir}; ("cd" ${usedir}; tar xf ../${pkgname}.tar);
rm -rf ${usedir}/debian
mkdir ${usedir}/debian
("cd" debinfo/${pkgname};
 for file in *; do
     if [ -d ${file} ]; then
	 cp -r ${file} ../${usedir}/debian;
     else
	 u8_xsubst ${file} ../../${usedir}/debian/${file} \
		   "VERSION" "${version}" \
		   "BASE_VERSION" "${base_version}" \
		   "FULL_VERSION" "${full_version}" \
		   "MINOR_VERSION" "${minor_version}" \
		   "MAJOR_VERSION" "${major_version}";
     fi;
 done);
cp -r debinfo/${pkgname} ${usedir}/debian
for x in BRANCH VERSION FULL_VERSION BASE_VERSION; do cp state/$x ${pkgname}; done

./deb_changelog ${pkgname} "${DISTRO}" "${version}" "${branch}" \
		"${STATUS}" "${URGENCY}" "${full_version}" \
	 1> ${usedir}/debian/changelog;


