#!/bin/sh

if [ -f packaging.sh ]; then
    . packaging.sh
else
    script_root=$(dirname $0);
    if [ -f ${script_root}/packaging.sh ]; then
	. ${script_root}/packaging.sh;
    else
	echo "Can't find packaging.sh init";
	exit 2;
    fi;
fi;

head_package=${PKGNAME}_${REL_VERSION}*.deb
sub_packages=$(ls ${PKGNAME}-*_${REL_VERSION}*.deb 2>/dev/null)
(sudo dpkg -i ${head_package}) && (if [ -n "${sub_packages}" ]; then sudo dpkg -i ${sub_packages}; fi);
