#!/bin/sh

if [ -f packaging.sh ]; then
    . packaging.sh
else
    script_root=$(dirname $0);
    if [ -f ${script_root}/packaging.sh ]; then
	. ${script_root}/packaging.sh;
    else
	echo "Can't find packaging.sh init";
	exit 2;
    fi;
fi;

export buildopt=
if [ -f state/NOSOURCE ]; then buildopt=-b; fi
workdir=${PKGNAME}
("cd" ${workdir};
 dpkg-buildpackage ${buildopt} -us -uc -sa -rfakeroot)
if [ ! -z "${GPGID}" ]; then
#    debsign -p${GPG} --re-sign -k${GPGID} dist/kno_@KNO_VERSION@*.changes && touch $@;
    debsign --re-sign -k${GPGID} kno_${REL_VERSION}*.changes
fi;
