#!/bin/sh

DEFAULT_PKGNAME=$(cat state/PKGNAME 2> /dev/null || echo libu8)
DEFAULT_DISTRO=$(cat state/DISTRO 2> /dev/null || echo debian)
export PKGNAME
export DISTRO

if [ $(basename "\\$0") = "mkdeb" ]; then
    PKGNAME=${1:-${DEFAULT_PKGNAME}}
    DISTRO=${2:-${DEFAULT_DISTRO}}
fi
    
echo ${PKGNAME} > state/PKGNAME;
echo ${DISTRO} > state/DISTRO;

export STATUS=${STATUS}
if [ -z "${STATUS}" ]; then
    if [ -f status ]; then
	STATUS=$(cat state/STATUS);
    else STATUS=stable;
    fi;
else
    echo ${STATUS} > state/STATUS;
fi;

export URGENCY=${URGENCY}
if [ -z "${URGENCY}" ]; then
    if [ -f urgency ]; then
	URGENCY=$(cat state/URGENCY);
    else URGENCY=medium;
    fi;
else
    echo ${URGENCY} > state/URGENCY;
fi;

start_build() {
    local pkgname=${1:${DEFAULT_PKGNAME}}
    local distro=${2:${DEFAULT_DISTRO}}
    echo ${pkgname} > state/PKGNAME
    echo ${distro} > state/DISTRO
    PKGNAME=${pkgname};
    DISTRO=${distro};
}

update_source() {
    local pkgname=${1:-${PKGNAME}}
    if [ ! -d ${pkgname}/.git ]; then
	git clone $(cat sources/${pkgname}) ${pkgname};
    else ("cd" ${pkgname}; git pull);
    fi
    ("cd" ${pkgname}; 
     u8_gitbranch > BRANCH; 
     u8_gitversion etc/base_version > VERSION; 
     u8_gitversion etc/base_version full > FULL_VERSION);
    ("cd" ${pkgname}; ./make_source_tar ../${pkgname}.tar);
}

debian_prepare() {
    local pkgname=${1:-${PKGNAME}}
    if [ -z "${DISTRO}" ]; then DISTRO=${DEFAULT_DISTRO}; fi
    echo "pkgname= ${pkgname}";
    rm -rf ${pkgname}/debian
    echo "cp -r debinfo/${pkgname} ${pkgname}/debian"
    cp -r debinfo/${pgkname} ${pkgname}/debian
    version=$(cat ${pkgname}/VERSION);
    branch=$(cat ${pkgname}/BRANCH);
    full_version=$(cat ${pkgname}/FULL_VERSION 2>/dev/null||echo $version);
     ./deb_changelog ${pkgname} ${DISTRO} ${version} ${branch} \
		     "${STATUS}" "${URGENCY}" "${full_version}" \
	 1> ${pkgname}/debian/changelog;
}

debian_build() {
    local pkgname=${1:-${PKGNAME}}
    ("cd" ${pkgname}; dpkg-buildpackage -b -us -uc -sa -rfakeroot);
}

if [ $(basename "\\$0") = "mkdeb" ]; then
    update_source ${PKGNAME} && 
	debian_prepare ${PKGNAME} && 
	debian_build ${PKGNAME};
fi;
