#!/bin/sh

if [ -f state/PKGNAME ]; then
    curpkg=$(cat state/PKGNAME);
fi;

case $1 in
    get|geti)
	upper=$(echo $2 | tr [a-z] [A-Z]);
	if [ -f state/${upper} ]; then
	    cat state/${upper};
	elif [ "$1" = geti ]; then
	    echo "No value for ${upper}";
	fi;
	exit;
	;;
    set)
	upper=$(echo $2 | tr [a-z] [A-Z]);
	echo $3 > state/${upper};
	exit;
	;;
    setup)
	for dir in sources/*; do
	    name=$(basename ${dir});
	    if [ "${name%~}" != "${name}" ]; then ./setsource ${name}; fi;
	done;
	exit;
	;;
    update)
	for dir in src/*; do
	    name=$(dirname ${dir});
	    setsource ${name};
	done;
	exit;
	;;
    *)
	upper=$(echo $1 | tr [a-z] [A-Z]);
	if [ -f state/${upper} ]; then
	    cat state/${upper};
	    exit;
	fi;
	;;
esac;

if [ -f "sources/$1" ]; then
    if [ -z "${PACKAGING_ROOT}" ]; then
	. packaging.sh;
    elif [ "${curpkg}" != "$1" ]; then
	. packaging.sh;
    fi;
else
    ACTION=$1; shift;
    . packaging.sh;
fi;

if [ "${PKGNAME}" != "${curpkg}" ]; then
    ./setsource ${PKGNAME};
fi;

case ${ACTION} in
    deb|debian)
	debtool ${curpkg} $@;
	exit;
	;;
    rpm|redhat)
	rpmtool ${curpkg} $@;
	exit;
	;;
    prep|prepare|pkg|package|install|push|make)
	${PKGTOOL} ${ACTION} $@;
	exit;
	;;
    pkg|package)
	${PKGTOOL} ${ACTION} $@;
	exit;
	;;
esac
   
