#!/bin/sh

usage () {
    echo "Usage: pkgset name [val]";
    echo "  Sets (or unsets) the packaging state variable *name*";
    echo "   when *val* is DROP, the value is removed.";
    echo "   when *val* is not given, the stdin is used";
}
if [ $# -lt 1 ] || [ $# -gt 2 ]; then
    usage;
    exit;
fi
if [ $# = 1 ]; then
   echo "pkgset: Reading value for $1 from stdin" >&2 ;
   cat > state/$1;
   if [ ! -s state/$1 ]; then
       echo "pkgset: Removing empty value" > &2;
       rm state/$1;
   else
       ls -l state/$1 >&2;
   fi;
elif [ "$2" = "DROP" ]; then
    rm state/$1;
else
    echo $2 > state/$1;
    ls -l state/$1 >&2 ;
fi;
