#!/bin/sh

if [ -f packaging.sh ]; then
    . packaging.sh
else
    script_root=$(dirname $0);
    if [ -f ${script_root}/packaging.sh ]; then
	. ${script_root}/packaging.sh;
    else
	echo "Can't find packaging.sh init";
	exit 2;
    fi;
fi;

BUILDRPM=buildrpm
RPMFLAGS=

${BUILDRPM} $(RPMFLAGS)
	   --define="_rpmdir $(RPMDIR)"
	   --define="_srcrpmdir $(RPMDIR)"
	   --nodeps -ta
	    staging/libu8-@U8VERSION@.tar.gz &&
		if [ -n "${GPGID}" ]; then
rpm --addsign --define="_gpg_name $(GPGID)"
		--define="__gpg_sign_cmd $(RPMGPG)"
		$(RPMDIR)/libu8-@U8VERSION@*.src.rpm
		$(RPMDIR)/*/libu8*-@U8VERSION@-*.rpm;
