#!/bin/sh

if [ -f packaging.sh ]; then
    . packaging.sh
else
    script_root=$(dirname $0);
    if [ -f ${script_root}/packaging.sh ]; then
	. ${script_root}/packaging.sh;
    else
	echo "Can't find packaging.sh init";
	exit 2;
    fi;
fi;

workdir=${1:-${PKGNAME}}
if [ -d ${workdir} ]; then
    logmsg "Removing existing build directory ${workdir}";
    rm -rf ${workdir};
fi
logmsg "Creating build directory at '${workdir}'"
rpm_root="${PKGNAME}-${MAJOR_VERSION}.${MINOR_VERSION}";
mkdir ${rpm_root};
("cd" ${rpm_root}; tar xf ../${PKGNAME}.tar);
tar cf ${PKGNAME}-${VERSION}.tar.gz ${rpm_root};
mv ${rpm_root} ${workdir}; 
u8_xsubst rpminfo/${PKGNAME}/${PKGNAME}.spec.in ${workdir}/${PKGNAME}.spec \
	  "VERSION" "${VERSION}" \
	  "MAJOR_VERSION" "${MAJOR_VERSION}" \
	  "MINOR_VERSION" "${MINOR_VERSION}"
rm -f ${PKGNAME}-${VERSION}.tar.gz;

