#!/bin/sh
pkgname=${1:-${PKGNAME}}
tarfile=${2:-${pkgname}.tar}
srcurl=$(cat sources/${pkgname})
srcdir=${pkgname}_src
if [ ! -d "${srcdir}" ]; then
    git clone $(cat sources/${pkgname}) ${srcdir};
else ("cd" ${srcdir}; git pull);
fi
echo ${srcdir} > state/SRCDIR
if [ -f ${srcdir}/etc/base_version ]; then
    ("cd" ${srcdir}; 
     u8_gitbranch > ../state/BRANCH;
     u8_gitversion etc/base_version > ../state/VERSION;
     u8_gitversion etc/base_version full > ../state/FULL_VERSION;
     cp etc/base_version ../state/BASE_VERSION;
     cut etc/base_version -d'.' -f 1 > ../state/MAJOR_VERSION;
     cut etc/base_version -d'.' -f 2 > ../state/MINOR_VERSION)
elif [ -f ${srcdir}/version ]; then
    version=$(knoconfig major).$(cat ${srcdir}/version);
    echo ${version} > state/BASE_VERSION;
    echo ${version} > state/FULL_VERSION;
    echo ${version} > state//VERSION;
    ("cd" ${srcdir}; u8_gitbranch > ../state/BRANCH);
    knoconfig major > state/MAJOR_VERSION;
    cut ${srcdir}/version -d'.' -f 1 > state/MINOR_VERSION;
fi;
if [ -x ${srcdir}/make_source_tar ]; then
    ("cd" ${srcdir}; ./make_source_tar ../${tarfile});
else 
    ("cd" ${srcdir}; git archive -o ../${tarfile} HEAD);
fi
