#!/bin/sh
PKGNAME=${1:-libu8};
CODENAME=${2:-debian};
VERSION=$3;
STATUS=${4:-stable};
URGENCY=${5:-medium};
DATE=`date -R`;

if [ -z "${STATUS}" ] || 
   [ ${STATUS} = "stable" ] || 
   [ ${STATUS} = "default" ]; then
    STATUS=
else
    STATUS="-${STATUS}";
fi;

if [ -z "${STATUS}" ]; then
  STATUSADJ=normal;
else
  STATUSADJ="${STATUS}";
fi
	
echo ${PKGNAME} \(${VERSION}-${CODENAME}\) ${CODENAME}${STATUS}\; urgency=${URGENCY}
echo
if [ -z ${DBRANCH} ]; then
    echo "  * ${GITID} ${STATUSADJ} point release of ${PKGNAME} for ${CODENAME} (${FULL_VERSION})"
else
    echo "  * ${GITID} ${STATUSADJ} point release of ${PKGNAME} (branch '${BRANCH}') for ${CODENAME} (${FULL_VERSION})"
fi;
echo
echo " -- Repository Manager <repoman@beingmeta.com>  ${DATE}"
echo
