#!/bin/sh

if [ -f packaging.sh ]; then
    . packaging.sh
else
    script_root=$(dirname $0);
    if [ -f ${script_root}/packaging.sh ]; then
	. ${script_root}/packaging.sh;
    else
	echo "Can't find packaging.sh init";
	exit 2;
    fi;
fi;

workdir=${1:-${PKGNAME}}
if [ -d ${workdir} ]; then
    logmsg "Removing existing build directory ${workdir}";
    rm -rf ${workdir};
fi
tarball="${PKGNAME}-${VERSION}.tar.gz"
rpm_root="${PKGNAME}-${MAJOR_VERSION}.${MINOR_VERSION}";
logmsg "Creating tarball ${tarball} for ${rpm_root}";
rm -f ${rpm_Root} && mkdir ${rpm_root} && ("cd" ${rpm_root}; tar xf ../${PKGNAME}.tar);
if [ -f rpminfo/${PKGNAME}/${PKGNAME}.spec.in ]; then
    u8_xsubst rpminfo/${PKGNAME}/${PKGNAME}.spec.in ${rpm_root}/${PKGNAME}.spec \
	      "VERSION" "${VERSION}" \
	      "MAJOR_VERSION" "${MAJOR_VERSION}" \
	      "MINOR_VERSION" "${MINOR_VERSION}";
elif [ -f rpminfo/${PKGNAME}.spec.in ]; then
    u8_xsubst rpminfo/${PKGNAME}/${PKGNAME}.spec.in ${rpm_root}/${PKGNAME}.spec \
	      "VERSION" "${VERSION}" \
	      "MAJOR_VERSION" "${MAJOR_VERSION}" \
	      "MINOR_VERSION" "${MINOR_VERSION}";
else
    echo "No RPM info for ${PKGNAME}";
    exit;
fi;
tar cf ${tarball} ${rpm_root};
logmsg "Establishing workdir ${workdir}";
mv ${rpm_root} ${workdir}; 


