#!/bin/sh

# Pushes a packaged artifact to a web endpoint, typically a repository server.
# Examples of REPO_URL:
#  http://nex.beingmeta.com/repository/kno/
#  http://packager:password@nex.beingmeta.com/repository/kno/

PUSH_URL=$1;
PUSH_LOGIN=$2;
shift; shift;
FILES=$*
CURL=$(which curl 2>/dev/null)
if [ -z "${CURL}" ]; then
    echo "Usage: curlpush [http..] [user:pass] [files...]";
    echo " No curl executable found!!";
    exit;
fi;

if [ -z "${PUSH_URL}" ]; then
    echo "Warning! No repository address to push to";
    exit 2;
fi;

if [ -z "${PUSH_LOGIN}" ]; then
    echo "Warning! No login info";
    exit 2;
fi;

for file in ${FILES}; do \
    done=no
    (${DEBUG_CURLPUSH} ${CURL} -f -u "${PUSH_LOGIN}" ${CURLOPTS} --upload-file "${file}" ${PUSH_URL}/$(basename ${file})) && done='yes';
    if [ "${done}" = yes ]; then
	echo "## Successfully pushed ${file} to ${PUSH_URL}" >&2;
    else
	echo "## Failed to push ${file} to ${PUSH_URL}" >&2;
	exit 2;
    fi;
done;
