#!/bin/sh

ACTION=$1; shift;

if [ -n "${ADDAPT}" ] && which addapt; then
    addapt ${ADDAPT};
fi;

if [ -n "${ADDAPT2}" ] && which addapt; then
    addapt ${ADDAPT2};
fi;

PKG_REVISION=1
if [ -f state/PKGNAME ]; then
    NO_PKGNAME=yes
fi;

if [ -f packaging.sh ]; then
    . ./packaging.sh
else
    script_root=$(dirname $0);
    if [ -f ${script_root}/packaging.sh ]; then
	. ${script_root}/packaging.sh;
    else
	echo "Can't find packaging.sh init";
	exit 2;
    fi;
fi;

logmsg "debtool ACTION=${ACTION} PKGNAME=${PKGNAME} VERSION=${VERSION} BRANCH=${BRANCH}";

DEBINFO=${PACKAGING_ROOT}/debinfo
DPKGNAME=${PKGNAME}
if [ -f ${DEBINFO}/${PKGNAME}/dpkgname.prop ]; then
    DPKGNAME=$(cat ${DEBINFO}/${PKGNAME}/dpkgname.prop);
fi

debprep() {
    local workdir=${1:-work/${PKGNAME}}
    if [ -d ${workdir} ]; then
	logmsg "Removing existing build directory ${workdir}";
	rm -rf ${workdir};
    fi
    logmsg "Creating build directory at '${workdir}'"
    mkdir ${workdir}; ("cd" ${workdir}; tar xf ../${PKGNAME}.tar);
    if [ ! -f state/NOSOURCE ]; then
	srctar=${PKGNAME}_${VERSION}.orig.tar.gz;
	logmsg "Creating source tarball at work/${srctar}";
	("cd" work; tar -czf ${srctar} ${PKGNAME});
    fi;
    if [ -d ${workdir}/debian ]; then rm -rf ${workdir}/debian; fi
    mkdir ${workdir}/debian
    logmsg "Setting up ${workdir}/debian";
    ("cd" ${DEBINFO}/${PKGNAME};
     for file in *; do
	 if [ ${file} != ${file%.ex} ]; then
	     # skip .ex files
	     :
	 elif [ -d ${file} ]; then
	     cp -r ${file} ../../${workdir}/debian;
	 elif [ "${file%.prop}" != "${file}" ]; then
	     :;
	 else
	     echo "Generating ../../${workdir}/debian/${file} from ${file}" > ../../output/${PKGNAME}/LOG;
	     ${TOOLS}/u8_xsubst -q ${file} ../../${workdir}/debian/${file} \
		       "VERSION" "${VERSION}"              \
		       "CHANNEL" "${CHANNEL}"                  \
		       "BRANCH" "${BRANCH}"                    \
		       "DISTRO" "${DISTRO}"                    \
		       "KNO_VERSION" "${KNO_VERSION}"          \
		       "KNO_MAJOR" "${KNO_MAJOR}"              \
		       "KNO_MINOR" "${KNO_MINOR}"              \
		       "BASE_VERSION" "${BASE_VERSION}"        \
		       "FULL_VERSION" "${FULL_VERSION}"        \
		       "MINOR_VERSION" "${MINOR_VERSION}"      \
		       "MAJOR_VERSION" "${MAJOR_VERSION}";
	 fi;
     done);
    for suffix in ${DISTRO}.${CHANNEL} ${DISTRO} ${CHANNEL}; do
	for custom in ${workdir}/debian/*.${suffix}; do
	    if [ -f ${custom} ]; then
		base=$(basename ${custom});
		base=${base%.${suffix}};
		dbgmsg "Using custom file ${custom} as ${base} in ${workdir}/debian/";
		mv ${custom} ${workdir}/debian/${base};
		# Remove other custom entries
		rm ${workdir}/debian/${base}.*;
	    fi;
	done;
    done;
    debchangelog 1> ${workdir}/debian/changelog;
}

debpackage() {
    local output_dir="output/${PKGNAME}/";
    local buildopt=
    if [ -f state/NOSOURCE ]; then buildopt=-b; fi
    local workdir="${1:-work/${PKGNAME}}"
    ("cd" ${workdir};
     dpkg-buildpackage ${buildopt} -us -uc -sa -rfakeroot)
    if [ ! -z "${GPGID}" ]; then
	#    debsign -p${GPG} --re-sign -k${GPGID} dist/kno_@KNO_VERSION@*.changes && touch $@;
	debsign --re-sign -k${GPGID} work/${PKGNAME}_${VERSION}*.changes
    fi;
    rm -f ${output_dir}/FILES ${output_dir}/${PKGNAME}*;
    local changes_file="$(ls work/${DPKGNAME}_${VERSION}*.changes)";
    grep "^ [0-9a-f]* [0-9]* [^ ]*$" ${changes_file} | \
    	cut - -d' ' -f 4 > ${output_dir}/FILES;
    for file in $(cat ${output_dir}/FILES); do
	if [ -f "work/${file}" ]; then mv work/${file} ${output_dir}; fi; done;
    echo ${FULL_VERSION} > ${output_dir}/FULL_VERSION
    mv work/${changes_file} ${output_dir};
}

debcheck() {
    local buildinfo=$(ls output/${PKGNAME}/${PKGNAME}_${VERSION}-${DISTRO}*.buildinfo 2>/dev/null);
    if [ -z "${buildinfo}" ]; then
	dbgmsg "No buildinfo found for output/${PKGNAME}/${PKGNAME}_${VERSION}-${DISTRO}...";
	return 1;
    elif [ -f "${buildinfo}" ]; then
	dbgmsg "File ${buildinfo} found";
	return 0;
    else
	dbgmsg "File ${buildinfo} not found";
	return 1;
    fi;
}

debinstall() {
    local decl_packages="$(cat debinfo/${PKGNAME}/install.prop 2>/dev/null)";
    local head_package=""
    local install_packages=""
    if [ -z "${decl_packages}" ]; then 
	head_package="output/${PKGNAME}/${DPKGNAME}_${VERSION}*.deb";
	install_packages="${head_package} $(ls output/${PKGNAME}/*-*_${VERSION}*.deb 2>/dev/null)";
    else
	for package in ${decl_packages}; do
	    match="$(ls output/${PKGNAME}/${package}_${VERSION}*.deb 2>/dev/null)";
	    if [ -n "${match}" ]; then
		install_packages="${install_packages} ${match}";
	    fi;
	done;
    fi;
    ${SUDO} dpkg -i ${install_packages};
}

debpush() {
    local head_package="output/${PKGNAME}/${DPKGNAME}_${VERSION}*.deb";
    local install_packages="${head_package} $(ls output/${PKGNAME}/*-*_${VERSION}*.deb 2>/dev/null)";
    if [ -z "${REPO}" ]; then
	${TOOLS}/curlpush ${install_packages};
    else
	${TOOLS}/curlpush ${install_packages} repo=${REPO};
    fi;
}

debchangelog() {
    local date="$(date -R)";
    local status_adj="${STATUS}";
    if [ -z "${status_adj}" ]; then status_adj=normal; fi
#    echo ${PKGNAME} \(${VERSION}-${DPKG_REVISION}-${CODENAME}\) ${codename} ${STATUS}\; urgency=${URGENCY}
#    echo ${PKGNAME} \(${VERSION}-${CODENAME}\) ${codename} ${STATUS}\; urgency=${URGENCY}
#    echo ${DPKGNAME} \(${VERSION}-${CODENAME}\) ${CODENAME} ${STATUS}\; urgency=${URGENCY}
    echo ${DPKGNAME} \(${VERSION}\) ${CODENAME} ${STATUS}\; urgency=${URGENCY}
    echo
    echo "  * ${GITID} ${STATUSADJ} point release of ${PKGNAME} (branch '${BRANCH}') for ${CODENAME} (${FULL_VERSION})"
    echo
    echo " -- ${REPOMAN}  ${date}"
    echo
}

saveout() {
    local saveto="${1:-${PKGNAME}.out}";
    local head_package="$(ls ${PKGNAME}_${VERSION}*.deb 2>/dev/null)";
    local sub_packages="$(ls ${PKGNAME}-*_${VERSION}*.deb 2>/dev/null)";
    local files="$(ls ${PKGNAME}_${VERSION}* 2>/dev/null)";
    if [ ! -d ${saveto} ]; then mkdir ${saveto}; fi
    mv ${head_package} ${sub_packages} ${files} ${saveto};
}

cleanout() {
    local head_package="$(ls output/${PKGNAME}/${PKGNAME}_${VERSION}*.deb 2>/dev/null)";
    local sub_packages="$(ls output/${PKGNAME}/${PKGNAME}-*_${VERSION}*.deb 2>/dev/null)";
    local files="$(ls output/${PKGNAME}/${PKGNAME}_${VERSION}* 2>/dev/null)";
    rm -f ${head_package} ${sub_packages} ${files};
}

cleanall() {
    cleanout;
    rm -f output/${PKGNAME}/*.deb output/${PKGNAME}/*.ddeb \
       output/${PKGNAME}/*.changes output/${PKGNAME}/*.dsc \
       output/${PKGNAME}/*.buildinfo output/${PKGNAME}/*.tar.*
}

case ${ACTION} in
    start|getsource|setsource|source)
	./setsource $*;
	;;
    prep)
	debprep $*;
	;;
    package|pkg|mkpkg|makepkg|build)
	import_state;
	if debcheck; then
	    echo "Nothing to do";
	    exit;
	elif [ "${LOGFILE}" = none ]; then
	    debpackage $@;
	elif [ -n "${LOGFILE}" ]; then
	    debpackage $* > ${LOGFILE};
	else
	    rm -f output/${PKGNAME}/LOG
	    debpackage $* > output/${PKGNAME}/LOG;
	fi;
	ls -l output/${PKGNAME}/
	;;
    make)
	if ! debcheck; then
	    ./setsource ${PKGNAME} && import_state && debprep ${PKGNAME} && debpackage ${PKGNAME};
	fi;
	;;
    install)
	import_state;
	INSTALLED=$(cat run/INSTALLED.${PKGNAME} 2>/dev/null||echo)
	if [ "${INSTALLED}" != "${FULL_VERSION}" ]; then
	    debinstall $* && echo ${FULL_VERSION} > run/INSTALLED.${PKGNAME};
	else
	    echo "The currently built version of ${PKGNAME} is already installed!";
	fi;
	;;
    push)
	PUSHED=$(cat output/${PKGNAME}/PUSHED 2>/dev/null||echo)
	XVERSION="${VERSION}-${CHANNEL}"
	if [ $# -gt 0 ] || [ "${PUSHED}" != "${XVERSION}" ]; then
	    debpush $* && echo ${XVERSION} > output/${PKGNAME}/PUSHED;
	else
	    echo "Already pushed ${PKGNAME} version ${XVERSION}";
	fi;
	;;
    update|latest|pushup)
	import_state;
	if [ -f output/${PKGNAME}/FULL_VERSION ] &&
	       [ "${FULL_VERSION}" = "$(cat output/${PKGNAME}/FULL_VERSION)" ]; then
	    # If the version we are building is already built in `output`, check if it's installed
	    INSTALLED=$(cat run/INSTALLED.${PKGNAME} 2>/dev/null||echo)
	    if [ "${INSTALLED}" != "${FULL_VERSION}" ]; then
		debinstall $* && echo ${FULL_VERSION} > run/INSTALLED.${PKGNAME};
	    fi;
	fi;
	(${SUDO} apt upgrade ${PKGNAME}) || (echo "Upgrade of ${PKGNAME} failed");
	APTVERSION=$(u8_aptversion ${PKGNAME});
	if [ "${APTVERSION}" != "${VERSION}" ]; then
	    ./setsource ${PKGNAME} && 
		debprep ${PKGNAME} && 
		debpackage ${PKGNAME} &&
		debinstall ${PKGNAME}  && 
		(if [ ${ACTION} = "pushup" ]; then debpush ${PKGNAME}; fi);
	else
	    echo "COOL! The package ${PKGNAME} doesn't need to be updated";
	fi;
	;;
    clean)
	dbgmsg "No debian cleanup for ${PKGNAME}";
	;;
    cleanout)
	cleanout;
	;;
    cleanall)
	cleanall;
	;;
    saveout)
	saveout $*;
	;;
    check)
	if debcheck; then
	    return 1;
	else
	    return 0;
	fi;
	;;
    *)
	logmsg "Unknown command '${ACTION}'";
	;;
esac
